services:
  mysql:
    image: mysql:8.0
    container_name: mysql-restaurante
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: restaurante_dam
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: