services:
  mysql:
    image: mysql:8.0
    container_name: mysql-restaurante
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: restaurante_dam
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springweb-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: