spring.application.name=springWeb

spring.main.banner-mode=off
#Quitar Logs iniciales
spring.main.log-startup-info=false

spring.datasource.url=jdbc:mysql://localhost:3306/restaurante_dam
spring.datasource.username=root
spring.datasource.password=1234
